### ISSUE TITLE
Code sample could be improved to allow for fluent API usage and the removal of the injection risk

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/azure-cosmos-db-graph-gremlindotnet-getting-started#8]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Not applicable.

### Any log messages given by the failure
Not applicable.

### Expected/desired behavior
A safer sample that makes more effective use of Gremlin.NET, if possible.

### OS and Version?
All.

### Versions
All.

### Mention any other details that might be useful
We know that Cosmos DB's graph API and Gremlin.NET's fluent API don't quite get on because Cosmos DB's graph API doesn't support bytecode. Moreover, we know that the only way to get Cosmos DB to process a request is to use `client.SubmitAsync()`. That leaves us with two problems: (1) the cost of writing, debugging, evolving, and maintaining string recipes for Gremlin is prohibitive; and (2) the string interpolation needed to parameterize the recipes introduces an injection risk. That leaves us with one alternative, parse the bytecode into a string and submit that.
Before I go and spend a bunch of time and effort doing this, I'd like to share some initial code for comment:

```csharp
public static string PrepareSubmission(Bytecode bytecode)
{
    // String optimization.
    // Constants avoid the cost of redefinition.
    const string emptyParentheses = "()";
    const string leftParenthesis = "(";
    const string rightParenthesis = ")";
    const string parameterSeparator = ", ";
    const string period = ".";
    const string escapedQuoteMark = "\'";
    const string quoteMark = "'";
    // Builder addresses cost of concatenation.
    var command = new StringBuilder();

    // Use a for-loop to access the counter.
    for (var i = 0; i < bytecode.StepInstructions.Count; i++)
    {
        // Use a variable to avoid array searches--makes the for-loop perform like a foreach-loop.
        var stepInstruction = bytecode.StepInstructions[i];
        if (i != 0)
        {
            command.Append(period);
        }

        command.Append(stepInstruction.OperatorName);
        if (stepInstruction.Arguments.Length == 0)
        {
            command.Append(emptyParentheses);
            continue;
        }

        command.Append(leftParenthesis);

        // Use a for-loop to access the counter.
        for (var j = 0; j < stepInstruction.Arguments.Length; j++)
        {
            // Use a variable to avoid array searches--makes the for-loop perform like a foreach-loop.
            var arg = stepInstruction.Arguments[j];
            if (j != 0)
            {
                command.Append(parameterSeparator);
            }

            if (arg is string input)
            {
                var scrubber = new StringBuilder(input);
                scrubber.Replace(quoteMark, escapedQuoteMark);

                command.Append(quoteMark);
                command.Append(scrubber.ToString());
                command.Append(quoteMark);

                continue;
            }

            command.Append(quoteMark);
            command.Append(arg.ToString());
            command.Append(quoteMark);
        }

        command.Append(rightParenthesis);
    }

    return command.ToString();
}
```

Instead of calling Next() or ToList() on the Gremlin API, just build up the query, pass the bytecode to the method, and use a wrapper to run `client.SubmitAsync()` and process the results.
Any comments or thoughts would be greatly appreciated.

**Comment by FlorianHockmann** [comment]
There are already a few libraries out there which seem to do basically what you're trying to achieve here, not sure if you're aware of them:

- https://github.com/ExRam/ExRam.Gremlinq
- https://github.com/evo-terren/Gremlin.Net.CosmosDb
- https://github.com/systemidx/CosmosDB.Gremlin.Fluent
- https://github.com/boonzaai/GremlinQuery.net

Regarding the injection risk you mention, I don't think that it's an issue if you can make sure that all parameters that could be controlled by users (and therefore an attacker) are sent as bindings. I wrote a more detailed description [in this answer on Stack Overflow](https://stackoverflow.com/a/44538936/6753576).

**Comment by SebGX** [comment]
Hi Florian,

Thanks for getting back to me, I appreciate it. A few questions if I may?

Do you think that it might be worthwhile to link to your notes on security as part of the Samples and readme so that new adopters (like myself) get all the info needed in one place? As I'm sure you know, half the challenge with being able to search for things effectively is learning the vocabulary so that the right keywords may be used in search engines.

Do you think that it might be worthwhile to call out Cosmos DB Gremlin API limitations such as not being able to update edges (at the time of writing). Again, new adopters can waste a lot of time thinking they've done something wrong only to figure out that Cosmos DB doesn't support something. By contrast, updating vertices works perfectly well. Further, some semantics such as `g.V().addE().from().to()` don't work at all and don't throw any errors. By contrast, `g.E().property()` returns an edge that looks like it has the new property; however, when `g.E()` is then used to fetch the edge with the "updated" property, there's no property.

In terms of the projects:
- Gremlinq is great in terms of the strong typing; however, it doesn't appear to deal with the manner in which queries must be submitted to Cosmos DB. Moreover, it's still under development and the project's team doesn't appear very large. Further, Gremlin.NET provides the exact same fluent API without the strong typing; so not certain that the strong typing is enough of a win to make up for the risks.

- Gremlin.Net.CosmosDB doesn't appear to be a good design or a stable project. The readme indicates that the project owner may bail on the project. Moreover, the project is a wrapper over the API, which--given the availability of bytecode--creates an unnecessary layer of indirection IMO.

- CosmosDB.Gremlin.Fluent and GremlinQuery.net have a combination of the issues of the first two.

Would love to know your thoughts on how we might make the overall experience better for new adopters so that negative experiences don't lead to the kind of frustration and anger that pushes people away from Cosmos DB.

Warm regards,
Seb

**Comment by FlorianHockmann** [comment]
Hi Seb,

I'm not working on Cosmos DB and I'm not even a user of it. I'm just working on Gremlin.Net which is why I'm watching this repo as the issues here are sometimes also interesting for Gremlin.Net in general.
So, I can't really say anything about the docs of Cosmos DB or its limitations.

The issues you mention with updating edges sound like they should get their own issue, but again, I don't really know much about Cosmos DB.

I only linked the projects because it sounded to me like you wanted to implement something very similar to what they are doing. Since I'm not using Cosmos DB, I haven't looked at any of them in greater detail.
In general, I can understand your assessment about the matureness of these libraries, but I assume that they only provide workarounds for the missing Gremlin Bytecode support of Cosmos DB. So, they could become obsolete once Cosmos DB does support Bytecode.

Regarding the frustrations of new users: Maybe this stops being an issue when Cosmos DB fully supports Gremlin Bytecode as users can then also just refer to TinkerPop's docs, including the freely available book [Practical Gremlin](http://kelvinlawrence.net/book/Gremlin-Graph-Guide.html), as there shouldn't be big differences from the usage perspective between Cosmos DB and other TinkerPop enabled graph databases. So, Cosmos DB would basically only have to point out differences specific to its implementation in their own docs.

**Comment by SebGX** [comment]
Hi Florian,

My mistake, I thought you were part of this project. From my perspective, the TinkerPop docs and the free book are awesome (the book has been the basis for my learning). Maybe someone from the Azure Cosmos DB team could take the content of this thread into consideration and update the docs with all of the relevant info?

Warm regards,
Seb

**Comment by olivertowers** [comment]
Cosmos DB Gremlin API does not support Fluent APIs directly - re-listing third-party tools that can provide fluent API wrappers from a previous response:

- https://github.com/ExRam/ExRam.Gremlinq
- https://github.com/evo-terren/Gremlin.Net.CosmosDb
- https://github.com/systemidx/CosmosDB.Gremlin.Fluent
- https://github.com/boonzaai/GremlinQuery.net

Gremlin API does support parameterized script requests per the Tinkerpop spec https://tinkerpop.apache.org/docs/current/reference/#parameterized-scripts
